import '../app/styles/globals.css'
import { Staatliches, Raleway } from 'next/font/google'
import Script from 'next/script'

const staatliches = Staatliches({
  subsets: ['latin'],
  weight: ['400'],
  variable: '--font-title',
  display: 'swap',
})

const raleway = Raleway({
  weight: ['400', '300'],
  subsets: ['latin'],
  variable: '--font-text',
  display: 'swap',
})

export const metadata = {
  title: 'Rogymar Portfolio',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${staatliches.variable} ${raleway.variable}`}>
      <body className='bg-light dark:bg-dark text-gris dark:text-darkLight'>{children}
        <Script id='theme-switcher' strategy='beforeInteractive'>
          {
            `if (localStorage.theme === 'dark' || (!('theme' in localStorage) && window.matchMedia('(prefers-color-scheme: dark)').matches)) {
            document.documentElement.classList.add('dark')
          } else {
            document.documentElement.classList.remove('dark')
          }
          `}
        </Script>
      </body>
    </html>
  )
}
