import '../app/styles/globals.css'
import { Staatliches, Raleway } from 'next/font/google'

const staatliches = Staatliches({ 
  subsets: ['latin'],
  weight: ['400'],
  variable: '--font-title',
  display: 'swap',
})

const raleway = Raleway({ 
  weight: ['400', '300'],
  subsets: ['latin'],
  variable: '--font-text',
  display: 'swap',
})

export const metadata = {
  title: 'Rogymar Portfolio',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${staatliches.variable} ${raleway.variable}`}>
      <body>{children}</body>
    </html>
  )
}
